language: php

services:
    - rabbitmq
    - redis

# cache vendor dirs
cache:
    apt: true
    directories:
        - vendor
        - $HOME/.composer/cache
        - node_modules
        - $HOME/.npm
        - $HOME/.yarn-cache

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

node_js:
    - "5"

env:
    - DB=mysql
    - DB=pgsql
    - DB=sqlite

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: CS_FIXER=run VALIDATE_TRANSLATION_FILE=run ASSETS=build DB=sqlite
    allow_failures:
        - php: nightly
        - php: 7.3

# exclude v1 branches
branches:
    except:
        - legacy

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;

install:
    - if [[ $ASSETS = build ]]; then source ~/.nvm/nvm.sh && nvm install 6.10; fi;
    - if [[ $ASSETS = build ]]; then npm install -g yarn@latest; fi;
    - if [[ $ASSETS = build ]]; then yarn install; fi;

before_script:
    - PHP=$TRAVIS_PHP_VERSION
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - composer self-update --no-progress
    - if [[ $DB = pgsql ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;

script:
    - travis_wait bash composer install -o --no-interaction --no-progress --prefer-dist

    - echo "travis_fold:start:prepare"
    # custom "prepare" for PG because the database should be created with a different user (see "before_script")
    - if [[ ! $DB = pgsql ]]; then make prepare DB=$DB; fi;
    - if [[ $DB = pgsql ]]; then make prepare-travis-pg DB=$DB; fi;
    - echo "travis_fold:end:prepare"

    - make fixtures

    - if [[ $VALIDATE_TRANSLATION_FILE = '' ]]; then SYMFONY_PHPUNIT_VERSION=6.5 ./bin/simple-phpunit -v ; fi;
    - if [[ $CS_FIXER = run ]]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;
    - if [[ $VALIDATE_TRANSLATION_FILE = run ]]; then php bin/console lint:yaml src/Wallabag/CoreBundle/Resources/translations -v ; fi;
    - if [[ $VALIDATE_TRANSLATION_FILE = run ]]; then php bin/console lint:yaml app/Resources/CraueConfigBundle/translations -v ; fi;
    - if [[ $VALIDATE_TRANSLATION_FILE = run ]]; then php bin/console lint:yaml src/Wallabag/UserBundle/Resources/translations -v ; fi;
    - if [[ $ASSETS = build ]]; then yarn run build:prod; fi;
